eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
   instance:
      instance-id: payment8002
      prefer-ip-address: true
      # 发送心跳的间隔时间 (默认 30 秒)
      lease-renewal-interval-in-seconds: 1
      # Eureka 服务端收到最后一次心跳后等待时间(默认 90 秒), 超时将剔除服务
      lease-expiration-duration-in-seconds: 2
