server:
  port: 10001
  max-http-header-size: 1024000

spring:
  application:
    name: sb_timescale-main-api

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy/MM/dd HH:mm:ss

  jpa:
    show-sql: on
    generate-ddl: on
    open-in-view: on
    hibernate:
      ddl-auto: update
      primary-dialect: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
    primary:
      database: postgresql

  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: redis #配置使用redis作为缓存
    redis:
      time-to-live: 7200000 #设置2个小时的存活时间
      key-prefix: HSL_PLUGINS_  #每个缓存空间的前缀
      use-key-prefix: true  #是否使用缓存前缀
      cache-null-values: true   #是否使用缓存空值，防止缓存穿透

  datasource:
    primary:
      jdbc-url: jdbc:postgresql://${pg.addr}/${pg.db}?&ssl=false
      driver-class-name: org.postgresql.Driver
      username: ${pg.username}
      password: ${pg.pwd}
      initial-size: 10
      max-active: 100
      min-idle: 3
      #验证连接的有效性
      test-while-idle: true
      #获取连接时候验证，会影响性能
      test-on-borrow: true
      validation-query: SELECT 1 FROM DUAL
      #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
      time-between-eviction-runs-millis: 60000
      #连接池空闲连接的有效时间 ，设置 10 分钟
      min-evictable-idle-time-millis: 60000
      maximum-pool-size: 20 # default is 10
      max-lifetime: 60000 # default is 30 minus
    initialization-mode: ${pg.init-mode}
    sql-script-encoding: utf-8
    separator: ;
    continue-on-error: true
  #    schema:
  #      - classpath:sql/schema-postgis.sql
  #    data:
  #      - classpath:sql/data-postgis.sql

  # Redis
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.pwd}
    database: ${redis.db}
    timeout: 20s # 连接超时时间（毫秒）
    # client-name: ${spring.application.name}
    lettuce:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: 1000 # 配置空闲连接回收间隔时间,min-idle才会生效,否则不生效
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"

javafamily:
  swagger:
    title: Main Apis
    version: 1.0
    contact:
      name: Jack Li
      email: lis@geovis.com.cn

logging:
  pattern:
    console: "{\"profile\": \"${spring.profiles.active}\", \"log_level\":\"%clr(${LOG_LEVEL_PATTERN})\", \"msg\": \"%replace(%m){'\"', \"'\"}\", \"date_time\":\"%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSSZ}}){faint}\",\"logger\":\"%clr(%-40.40logger{39}){cyan}\",\"thread\":\"%clr([%15.15t]){faint}\",\"ServiceName\": \"${spring.application.name}\",\"requestId\":\"%X{requestId}\",\"IP\":\"%X{traceIp}\",\"PID\":\"${PID:- }\",\"Token\":\"%X{Authorization}\",\"exp\":\"${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}\"}%n"
    file: "{\"profile\": \"${spring.profiles.active}\", \"log_level\":\"%clr(${LOG_LEVEL_PATTERN})\",\"msg\":\"%replace(%m){'\"', \"'\"}\",\"date_time\":\"%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSSZ}}){faint}\",\"logger\":\"%clr(%-40.40logger{39}){cyan}\",\"thread\":\"%clr([%15.15t]){faint}\",\"ServiceName\": \"${spring.application.name}\",\"requestId\":\"%X{requestId}\",\"IP\":\"%X{traceIp}\",\"PID\":\"${PID:- }\",\"Token\":\"%X{Authorization}\",\"exp\":\"${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}\"}%n"
  file:
    name: ./logs/app-${spring.application.name}-${spring.profiles.active}.log

