server:
   port: 9079

spring:
#   profiles:
#      active: dev

   application:
      name: thunderstorm-xxl-executor

   jackson:
      default-property-inclusion: ALWAYS
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

   jpa:
      show-sql: on
      generate-ddl: on
      open-in-view: on
      hibernate:
         primary-dialect: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
      primary:
         database: postgresql

   # Redis
   redis:
      #    host: 192.168.100.17
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.pwd}
      database: 1
      timeout: 20s # 连接超时时间（毫秒）
      #    client-name: whp
      lettuce:
         pool:
            max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10 # 连接池中的最大空闲连接
            min-idle: 0 # 连接池中的最小空闲连接
            time-between-eviction-runs: 1000 # 配置空闲连接回收间隔时间,min-idle才会生效,否则不生效

   datasource:
      primary:
         jdbc-url: jdbc:postgresql://${pg.addr}/${pg.db}?&ssl=false
         driver-class-name: org.postgresql.Driver
         username: ${pg.username}
         password: ${pg.pwd}
         #验证连接的有效性
         test-while-idle: true
         #获取连接时候验证，会影响性能
         test-on-borrow: true
         validation-query: SELECT 1 FROM DUAL
         #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
         time-between-eviction-runs-millis: 300000
         #连接池空闲连接的有效时间 ，设置30分钟
         min-evictable-idle-time-millis: 1800000
         maximum-pool-size: 50 # default is 10
         max-lifetime: 60000 # default is 30 minus
      initialization-mode: never

xxl:
   job:
      admin:
         addresses:  ${XXL_ADMIN_ADDR:http://192.168.100.252/job-admin}
      executor:
         appname: ${spring.application.name}
         address:
         ip: ${EXECUTOR_IP:192.168.100.252}
         port: 9007
         logretentiondays: 3
         logpath: classpath:logback.xml
      accessToken:

javafamily:
   notify:
      feishu:
         enabled: off
         hook-url: https://open.feishu.cn/open-apis/bot/v2/hook/${FEISHU_TOKEN:ef6aa3d1-4696-4852-9489-f611b42b6444}

mlog:
   oss:
      minio:
         end-point: ${minio.end-point}
         user: ${minio.user}
         password: ${minio.pwd}
         default-bucket: thunderstorm
         prefix:
            - ^date^
