server:
   port: 80
   servlet:
      context-path: /

spring:

   redis:
      database: 11
      client-name: thunderstorm-auth-locale

   cache:
      redis:
         key-prefix: thunderstorm-auth-locale-
