springfox:
   documentation:
      swagger:
         v2:
            host: 106.75.18.229/thunderstorm-auth

spring:

   redis:
      client-name: thunderstorm-auth-dev
      database: 11

   cache:
      redis:
         key-prefix: thunderstorm-auth-dev-
