server:
   port: 80

es:
   host: localhost
   port: 9200
mlog:
#   http:
#      keep-alive-target-host:
#         - www.gfapi.mlogcn.com: 10
#         - gfapi.mlogcn.com: 10s

   weather:
      baseUri: http://117.50.104.9:8081
      realTime:
         api: /v1/realtime/weather/now
         params: lonlat

#      baseUri: http://gfapi.mlogcn.com
#      realTime:
#         api: /weather/v001/now
#         params: areacode,key

logging:
   logback:
      rollingpolicy:
         max-file-size: 100MB
         max-history: 7
