server:
   port: 8082
spring:
   application:
      name: grpc-client

grpc:
   client:
      grpc-server:
         address: 'static://127.0.0.1:9091'
         enableKeepAlive: true
         keepAliveWithoutCalls: true
         negotiationType: plaintext
