server: 
  port: 7002
  
eureka: 
  instance: 
    hostname: node2.com 
  client: 
    register-with-eureka: false 
    fetch-registry: false 
    service-url: 
      defaultZone: http://node3.com:7003/eureka/,http://node1.com:7001/eureka/ 
