server:
   port: 80

spring:
   application:
      name: sb-flowable

   jpa:
      #show-sql: on
      generate-ddl: on
      open-in-view: on
      hibernate:
         ddl-auto: update
         primary-dialect: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
      primary:
         database: postgresql

   datasource:
      primary:
         jdbc-url: jdbc:postgresql://${pg.addr}/${pg.db}?&ssl=false
         driver-class-name: org.postgresql.Driver
         username: ${pg.username}
         password: ${pg.pwd}
         initial-size: 10
         max-active: 100
         min-idle: 3
         #\u9A8C\u8BC1\u8FDE\u63A5\u7684\u6709\u6548\u6027
         test-while-idle: true
         #\u83B7\u53D6\u8FDE\u63A5\u65F6\u5019\u9A8C\u8BC1\uFF0C\u4F1A\u5F71\u54CD\u6027\u80FD
         test-on-borrow: true
         validation-query: SELECT 1 FROM DUAL
         #\u7A7A\u95F2\u8FDE\u63A5\u56DE\u6536\u7684\u65F6\u95F4\u95F4\u9694\uFF0C\u4E0Etest-while-idle\u4E00\u8D77\u4F7F\u7528\uFF0C\u8BBE\u7F6E5\u5206\u949F
         time-between-eviction-runs-millis: 60000
         #\u8FDE\u63A5\u6C60\u7A7A\u95F2\u8FDE\u63A5\u7684\u6709\u6548\u65F6\u95F4 \uFF0C\u8BBE\u7F6E 10 \u5206\u949F
         min-evictable-idle-time-millis: 60000
         maximum-pool-size: 20 # default is 10
         max-lifetime: 60000 # default is 30 minus
      initialization-mode: ${pg.init-mode}
      sql-script-encoding: utf-8
      separator: ;
      continue-on-error: true
