spring:
   application:
      name: sb-service1
   datasource:
      url: jdbc:postgresql://161.189.73.116:5432/db_jilin
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: yiji_0716

mybatis-plus:
   global-config:
      db-config:
         table-prefix: t_
   mapper-locations: classpath*:/mapper/**/*.xml
   type-aliases-package: mlog.demo.client.entity
   configuration:
      map-underscore-to-camel-case: on
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
   port: 9411

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always

