server:
   port: 9527
   
spring:
   application:
      name: cloud-zuul-gateway

eureka:
   client: #客户端注册进eureka服务列表内
      service-url:
         defaultZone: http://node1.com:7001/eureka/,http://node2.com:7002/eureka/,http://node3.com:7003/eureka/ 
   instance:
      instance-id: gateway-9527.com
      prefer-ip-address: true #访问路径可以显示IP地址
      
zuul: 
  # ignored-services: cloud-dept
  ignored-services: "*"
  prefix: /jf
  routes: 
    mydept.serviceId: cloud-dept
    mydept.path: /mydept/**

info:
   app.name: javafamily-cloud
   commany: www.javfamily.club
   artifactId: $project.artifactId$
   version: $project.version$
