server:
  port: 8200

spring:
  application:
    name: consumer-user

eureka:
  instance:
    prefer-ip-address: true # \u6CE8\u518C\u670D\u52A1\u65F6\u4F7F\u7528\u670D\u52A1\u7684 IP \u5730\u5740\u8FDB\u884C\u6CE8\u518C.

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # \u81EA\u5B9A\u4E49\u6CE8\u518C\u4E2D\u5FC3\u7684\u6CE8\u518C\u5730\u5740
