

spring:
   application:
      name: sb-service1
   datasource:
      url: jdbc:postgresql://10.1.109.140:5432/db_test
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: geoVis0605

   # kafka
   kafka:
      bootstrap-servers:  10.1.109.140:9092,10.1.109.141:9092,10.1.109.98:9092
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
         group-id: sb-kafka-consumer
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis-plus:
   global-config:
      db-config:
         table-prefix: t_
   mapper-locations: classpath*:/mapper/**/*.xml
   type-aliases-package: mlog.demo.client.entity
   configuration:
      map-underscore-to-camel-case: on
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
   port: 9411

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always

logging:
   level:
      org.apache.kafka: INFO



