server:
  port: 80
  
eureka:
   client: #客户端注册进eureka服务列表内
      register-with-eureka: false     #false表示不向注册中心注册自己。
      service-url:
         defaultZone: http://node1.com:7001/eureka/,http://node2.com:7002/eureka/,http://node3.com:7003/eureka/

         
# 开启客户端 Hystrix 熔断器
feign:
   hystrix:
      enabled: true
