springfox:
   documentation:
      swagger:
         v2:
            host: 106.75.18.229/thunderstorm-api

spring:

   redis:
      client-name: thunderstorm-dev
      database: 1

   cache:
      redis:
         key-prefix: thunderstorm-dev-
